name: Order Service

on:
  push:
    branches: [main]
    paths:
      - 'order-service/**'
      - '.github/workflows/_service.yml'
      - '.github/workflows/order-service.yml'
  pull_request:
    branches: [main]
    paths:
      - 'order-service/**'
      - '.github/workflows/_service.yml'
      - '.github/workflows/order-service.yml'

concurrency:
  group: order-service-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_service.yml
    with:
      service: order-service
      function-name: order-consumer
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
